apps/webshop_restaurant_web/lib/webshop_restaurant_web/router.ex
defmodule WebshopRestaurantWeb.Router do
  use WebshopRestaurantWeb, :router

  pipeline :allowed_for_users do
    plug WebshopRestaurantWeb.Plugs.AuthorizationPlug, ["Admin", "User"]
  end

  pipeline :allowed_for_admins do
    plug WebshopRestaurantWeb.Plugs.AuthorizationPlug, ["Admin"]
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug WebshopRestaurantWeb.Plugs.Locale
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug WebshopRestaurantWeb.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :apiAuth do
    plug WebshopRestaurantWeb.Plug.ApiAuthorization
  end

  scope "/", WebshopRestaurantWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
    get "/signup", SessionController, :signup
    post "/signup", SessionController, :signup_user
    get "/unauthenticatedApi", PageController, :unauthenticatedApi
  end

  scope "/", WebshopRestaurantWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_users]

    get "/user_scope", PageController, :user_index
    resources "/products", ProductController, only: [:index, :show]
    resources "/carts", CartController
    get "/add_cart/:id", CartController, :add_cart
    get "/delete_product/:id", CartController, :delete_product
    get "/create_order", OrderController, :create_order
    get "/my_orders", OrderController, :my_orders
    resources "/orders", OrderController, only: [:show]
    get "/discount_code/:id", CartController, :discount_form
    post "/discount_code", CartController, :apply_discount

  end

  scope "/admin", WebshopRestaurantWeb do
    pipe_through [:browser, :auth, :ensure_auth, :allowed_for_admins]

    resources "/users", UserController
    resources "/orders", OrderController
    resources "/categories", CategoryController
    resources "/products", ProductController
    get "/", PageController, :admin_index
    get "/create_order", OrderController, :create_order
    get "/all_orders", OrderController, :index
  end

   scope "/api", WebshopRestaurantWeb do
    post "/sign_in", SessionController, :create
    delete "/sign_out", SessionController, :delete
    pipe_through [:api, :apiAuth]
    resources "/products", Api.ProductController

  #    resources "/products", ProductController
  #  end
  end

  # Other scopes may use custom stacks.
  # scope "/api", WebshopRestaurantWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: WebshopRestaurantWeb.Telemetry
    end
  end
end

apps/webshop_restaurant_web/lib/webshop_restaurant_web/views/layout_view.ex
defmodule WebshopRestaurantWeb.LayoutView do
  use WebshopRestaurantWeb, :view

  def new_locale(conn, locale, language_title) do
    "<a href=\"#{Routes.page_path(conn, :index, locale: locale)}\">#{language_title}</a>" |> raw
  end
end

apps/webshop_restaurant_web/lib/webshop_restaurant_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Webshop Restaurant</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
        <ul>
          <li><a href="/"><%=gettext "Home"%></a></li>
          <%= if WebshopRestaurantWeb.UserView.loggedin(@conn) do %>
          <%= if WebshopRestaurantWeb.UserView.is_admin(@conn) do %>
          <li><a href="<%= Routes.category_path(@conn, :index)%>"><%=gettext "Category"%></a></li>
          <li><a href="<%= Routes.order_path(@conn, :index)%>"><%=gettext "All Orders"%></a></li>
          <li><a href="<%= Routes.user_path(@conn, :index)%>"><%=gettext "Users"%></a></li>
          <% end %>
          
          <li><a href="<%= Routes.product_path(@conn, :index)%>"><%=gettext "Product"%></a></li>
          <%= if !WebshopRestaurantWeb.UserView.is_admin(@conn) do %>
              <li><a href="<%= Routes.order_path(@conn, :my_orders)%>"><%=gettext "My Orders"%></a></li>
          <% end %>
          <li><a href="<%= Routes.cart_path(@conn, :index)%>"><%=gettext "Cart"%></a></li>
          <li><a href="<%= Routes.session_path(@conn, :logout)%>"><%=gettext "Logout"%></a></li>
          <%= else %>
            <li><a href="<%= Routes.session_path(@conn, :new)%>"><%=gettext "Login"%></a></li>
          <% end %>

        </ul>
      </nav>
      <ul>
        <li><%= new_locale @conn, :en, gettext "English" %></li>
        <li><%= new_locale @conn, :nl, gettext "Dutch" %></li>
      </ul>
      
      <img src="<%= Routes.static_path(@conn, "/images/logotext.png") %>" alt="Brasserie Pakenhof Logo"/>

      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>